swagger: "2.0"
info:
    title: Api for deployments
    version: 0.0.1
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/deployments:
        get:
            tags:
                - deployments
            summary: list deployments
            operationId: deployments#list
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            type: string
                            example: Corrupti doloribus suscipit.
            schemes:
                - http
        post:
            tags:
                - deployments
            summary: upsert deployments
            operationId: deployments#upsert
            parameters:
                - name: UpsertRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/DeploymentsUpsertRequestBody'
                    required:
                        - name
                        - containers
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
    /api/deployments/{deploymentName}:
        get:
            tags:
                - deployments
            summary: get deployments
            operationId: deployments#get
            parameters:
                - name: deploymentName
                  in: path
                  description: Name of the Deployment
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/DeploymentsGetResponseBody'
                        required:
                            - name
                            - containers
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/DeploymentsGetDeploymentNotFoundResponseBody'
            schemes:
                - http
    /api/deployments/{deploymentName}/delete:
        get:
            tags:
                - deployments
            summary: delete deployments
            operationId: deployments#delete
            parameters:
                - name: deploymentName
                  in: path
                  description: Name of the Deployment
                  required: true
                  type: string
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/DeploymentsDeleteDeploymentNotFoundResponseBody'
            schemes:
                - http
    /api/deployments/{deploymentName}/view:
        get:
            tags:
                - deployments
            summary: get deployments
            operationId: deployments#get#1
            parameters:
                - name: deploymentName
                  in: path
                  description: Name of the Deployment
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/DeploymentsGetResponseBody'
                        required:
                            - name
                            - containers
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/DeploymentsGetDeploymentNotFoundResponseBody'
            schemes:
                - http
    /openapi3.json:
        get:
            tags:
                - deployments
            summary: Download ./gen/http/openapi3.json
            operationId: deployments#/openapi3.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    ContainerRequestBody:
        title: ContainerRequestBody
        type: object
        properties:
            image:
                type: string
                example: Repudiandae quod necessitatibus et voluptas.
            name:
                type: string
                example: Temporibus qui qui sint est dolorum.
            services:
                type: array
                items:
                    type: string
                    example: Animi voluptas sed quas.
                example:
                    - Repellat distinctio doloribus sequi.
                    - Temporibus laboriosam fugit et consequatur illum.
                    - Esse suscipit totam.
            usedParams:
                type: array
                items:
                    $ref: '#/definitions/ParameterUsageRequestBody'
                example:
                    - environment:
                        - Voluptatem laboriosam perspiciatis est.
                        - Est veritatis.
                        - Quo aut recusandae.
                        - Temporibus asperiores et voluptatem a consequatur ut.
                      files:
                        - Voluptatem necessitatibus labore aliquam consequatur est.
                        - Ullam voluptate esse.
                        - Aut et totam voluptatem quia illo voluptate.
                      name: z
                    - environment:
                        - Voluptatem laboriosam perspiciatis est.
                        - Est veritatis.
                        - Quo aut recusandae.
                        - Temporibus asperiores et voluptatem a consequatur ut.
                      files:
                        - Voluptatem necessitatibus labore aliquam consequatur est.
                        - Ullam voluptate esse.
                        - Aut et totam voluptatem quia illo voluptate.
                      name: z
        example:
            image: Quia minus et voluptatum vel.
            name: Sint dolores fugiat est dicta necessitatibus.
            services:
                - Adipisci quis exercitationem.
                - Eaque a.
            usedParams:
                - environment:
                    - Voluptatem laboriosam perspiciatis est.
                    - Est veritatis.
                    - Quo aut recusandae.
                    - Temporibus asperiores et voluptatem a consequatur ut.
                  files:
                    - Voluptatem necessitatibus labore aliquam consequatur est.
                    - Ullam voluptate esse.
                    - Aut et totam voluptatem quia illo voluptate.
                  name: z
                - environment:
                    - Voluptatem laboriosam perspiciatis est.
                    - Est veritatis.
                    - Quo aut recusandae.
                    - Temporibus asperiores et voluptatem a consequatur ut.
                  files:
                    - Voluptatem necessitatibus labore aliquam consequatur est.
                    - Ullam voluptate esse.
                    - Aut et totam voluptatem quia illo voluptate.
                  name: z
        required:
            - name
            - image
    ContainerResponseBody:
        title: ContainerResponseBody
        type: object
        properties:
            image:
                type: string
                example: Fuga voluptatem quisquam quia et.
            name:
                type: string
                example: Enim ea.
            services:
                type: array
                items:
                    type: string
                    example: Nobis in animi excepturi.
                example:
                    - Sunt ipsam quia accusantium.
                    - Dolores nam neque soluta similique maiores pariatur.
                    - Nemo nemo praesentium aspernatur accusantium.
                    - Ut culpa.
            usedParams:
                type: array
                items:
                    $ref: '#/definitions/ParameterUsageResponseBody'
                example:
                    - environment:
                        - Veritatis ea.
                        - Placeat dolore asperiores.
                        - Vitae omnis architecto maxime nesciunt voluptatibus.
                      files:
                        - Aut reprehenderit ad odit est.
                        - Fugit deserunt hic a architecto.
                        - Commodi reprehenderit.
                        - Sed est enim quidem ad illum distinctio.
                      name: "7"
                    - environment:
                        - Veritatis ea.
                        - Placeat dolore asperiores.
                        - Vitae omnis architecto maxime nesciunt voluptatibus.
                      files:
                        - Aut reprehenderit ad odit est.
                        - Fugit deserunt hic a architecto.
                        - Commodi reprehenderit.
                        - Sed est enim quidem ad illum distinctio.
                      name: "7"
                    - environment:
                        - Veritatis ea.
                        - Placeat dolore asperiores.
                        - Vitae omnis architecto maxime nesciunt voluptatibus.
                      files:
                        - Aut reprehenderit ad odit est.
                        - Fugit deserunt hic a architecto.
                        - Commodi reprehenderit.
                        - Sed est enim quidem ad illum distinctio.
                      name: "7"
                    - environment:
                        - Veritatis ea.
                        - Placeat dolore asperiores.
                        - Vitae omnis architecto maxime nesciunt voluptatibus.
                      files:
                        - Aut reprehenderit ad odit est.
                        - Fugit deserunt hic a architecto.
                        - Commodi reprehenderit.
                        - Sed est enim quidem ad illum distinctio.
                      name: "7"
        example:
            image: Praesentium rem enim minima dolorem impedit.
            name: Laboriosam corporis qui commodi sunt.
            services:
                - Corporis eum.
                - Perferendis et officiis quia sunt aperiam.
                - Qui sit quis eligendi adipisci.
            usedParams:
                - environment:
                    - Veritatis ea.
                    - Placeat dolore asperiores.
                    - Vitae omnis architecto maxime nesciunt voluptatibus.
                  files:
                    - Aut reprehenderit ad odit est.
                    - Fugit deserunt hic a architecto.
                    - Commodi reprehenderit.
                    - Sed est enim quidem ad illum distinctio.
                  name: "7"
                - environment:
                    - Veritatis ea.
                    - Placeat dolore asperiores.
                    - Vitae omnis architecto maxime nesciunt voluptatibus.
                  files:
                    - Aut reprehenderit ad odit est.
                    - Fugit deserunt hic a architecto.
                    - Commodi reprehenderit.
                    - Sed est enim quidem ad illum distinctio.
                  name: "7"
        required:
            - name
            - image
    DeploymentsDeleteDeploymentNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: delete_DeploymentNotFound_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    DeploymentsGetDeploymentNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: get_DeploymentNotFound_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    DeploymentsGetResponseBody:
        title: DeploymentsGetResponseBody
        type: object
        properties:
            containers:
                type: array
                items:
                    $ref: '#/definitions/ContainerResponseBody'
                example:
                    - image: Eos nostrum adipisci.
                      name: Aut molestiae vero tempore quasi.
                      services:
                        - Enim unde consequatur amet iusto.
                        - Expedita fuga.
                        - Libero reprehenderit mollitia repellendus provident.
                        - Autem vitae ea adipisci itaque qui ut.
                      usedParams:
                        - environment:
                            - Veritatis ea.
                            - Placeat dolore asperiores.
                            - Vitae omnis architecto maxime nesciunt voluptatibus.
                          files:
                            - Aut reprehenderit ad odit est.
                            - Fugit deserunt hic a architecto.
                            - Commodi reprehenderit.
                            - Sed est enim quidem ad illum distinctio.
                          name: "7"
                        - environment:
                            - Veritatis ea.
                            - Placeat dolore asperiores.
                            - Vitae omnis architecto maxime nesciunt voluptatibus.
                          files:
                            - Aut reprehenderit ad odit est.
                            - Fugit deserunt hic a architecto.
                            - Commodi reprehenderit.
                            - Sed est enim quidem ad illum distinctio.
                          name: "7"
                minItems: 1
            name:
                type: string
                example: Deleniti delectus.
            params:
                type: array
                items:
                    $ref: '#/definitions/ParameterResponseBody'
                example:
                    - name: tj
                      source: static
                      type: password
                    - name: tj
                      source: static
                      type: password
                    - name: tj
                      source: static
                      type: password
                    - name: tj
                      source: static
                      type: password
        example:
            containers:
                - image: Eos nostrum adipisci.
                  name: Aut molestiae vero tempore quasi.
                  services:
                    - Enim unde consequatur amet iusto.
                    - Expedita fuga.
                    - Libero reprehenderit mollitia repellendus provident.
                    - Autem vitae ea adipisci itaque qui ut.
                  usedParams:
                    - environment:
                        - Veritatis ea.
                        - Placeat dolore asperiores.
                        - Vitae omnis architecto maxime nesciunt voluptatibus.
                      files:
                        - Aut reprehenderit ad odit est.
                        - Fugit deserunt hic a architecto.
                        - Commodi reprehenderit.
                        - Sed est enim quidem ad illum distinctio.
                      name: "7"
                    - environment:
                        - Veritatis ea.
                        - Placeat dolore asperiores.
                        - Vitae omnis architecto maxime nesciunt voluptatibus.
                      files:
                        - Aut reprehenderit ad odit est.
                        - Fugit deserunt hic a architecto.
                        - Commodi reprehenderit.
                        - Sed est enim quidem ad illum distinctio.
                      name: "7"
                - image: Eos nostrum adipisci.
                  name: Aut molestiae vero tempore quasi.
                  services:
                    - Enim unde consequatur amet iusto.
                    - Expedita fuga.
                    - Libero reprehenderit mollitia repellendus provident.
                    - Autem vitae ea adipisci itaque qui ut.
                  usedParams:
                    - environment:
                        - Veritatis ea.
                        - Placeat dolore asperiores.
                        - Vitae omnis architecto maxime nesciunt voluptatibus.
                      files:
                        - Aut reprehenderit ad odit est.
                        - Fugit deserunt hic a architecto.
                        - Commodi reprehenderit.
                        - Sed est enim quidem ad illum distinctio.
                      name: "7"
                    - environment:
                        - Veritatis ea.
                        - Placeat dolore asperiores.
                        - Vitae omnis architecto maxime nesciunt voluptatibus.
                      files:
                        - Aut reprehenderit ad odit est.
                        - Fugit deserunt hic a architecto.
                        - Commodi reprehenderit.
                        - Sed est enim quidem ad illum distinctio.
                      name: "7"
            name: Soluta delectus et fugiat nihil nostrum beatae.
            params:
                - name: tj
                  source: static
                  type: password
                - name: tj
                  source: static
                  type: password
                - name: tj
                  source: static
                  type: password
        required:
            - name
            - containers
    DeploymentsUpsertRequestBody:
        title: DeploymentsUpsertRequestBody
        type: object
        properties:
            containers:
                type: array
                items:
                    $ref: '#/definitions/ContainerRequestBody'
                example:
                    - image: Quisquam sed.
                      name: Dignissimos et nemo sunt commodi iste.
                      services:
                        - Rem fugiat est.
                        - Quas enim magnam libero consectetur qui nesciunt.
                        - Quam libero.
                      usedParams:
                        - environment:
                            - Voluptatem laboriosam perspiciatis est.
                            - Est veritatis.
                            - Quo aut recusandae.
                            - Temporibus asperiores et voluptatem a consequatur ut.
                          files:
                            - Voluptatem necessitatibus labore aliquam consequatur est.
                            - Ullam voluptate esse.
                            - Aut et totam voluptatem quia illo voluptate.
                          name: z
                        - environment:
                            - Voluptatem laboriosam perspiciatis est.
                            - Est veritatis.
                            - Quo aut recusandae.
                            - Temporibus asperiores et voluptatem a consequatur ut.
                          files:
                            - Voluptatem necessitatibus labore aliquam consequatur est.
                            - Ullam voluptate esse.
                            - Aut et totam voluptatem quia illo voluptate.
                          name: z
                    - image: Quisquam sed.
                      name: Dignissimos et nemo sunt commodi iste.
                      services:
                        - Rem fugiat est.
                        - Quas enim magnam libero consectetur qui nesciunt.
                        - Quam libero.
                      usedParams:
                        - environment:
                            - Voluptatem laboriosam perspiciatis est.
                            - Est veritatis.
                            - Quo aut recusandae.
                            - Temporibus asperiores et voluptatem a consequatur ut.
                          files:
                            - Voluptatem necessitatibus labore aliquam consequatur est.
                            - Ullam voluptate esse.
                            - Aut et totam voluptatem quia illo voluptate.
                          name: z
                        - environment:
                            - Voluptatem laboriosam perspiciatis est.
                            - Est veritatis.
                            - Quo aut recusandae.
                            - Temporibus asperiores et voluptatem a consequatur ut.
                          files:
                            - Voluptatem necessitatibus labore aliquam consequatur est.
                            - Ullam voluptate esse.
                            - Aut et totam voluptatem quia illo voluptate.
                          name: z
                minItems: 1
            name:
                type: string
                example: Quia assumenda cupiditate est.
            params:
                type: array
                items:
                    $ref: '#/definitions/ParameterRequestBody'
                example:
                    - name: bym
                      source: static
                      type: bool
                    - name: bym
                      source: static
                      type: bool
                    - name: bym
                      source: static
                      type: bool
                    - name: bym
                      source: static
                      type: bool
        example:
            containers:
                - image: Quisquam sed.
                  name: Dignissimos et nemo sunt commodi iste.
                  services:
                    - Rem fugiat est.
                    - Quas enim magnam libero consectetur qui nesciunt.
                    - Quam libero.
                  usedParams:
                    - environment:
                        - Voluptatem laboriosam perspiciatis est.
                        - Est veritatis.
                        - Quo aut recusandae.
                        - Temporibus asperiores et voluptatem a consequatur ut.
                      files:
                        - Voluptatem necessitatibus labore aliquam consequatur est.
                        - Ullam voluptate esse.
                        - Aut et totam voluptatem quia illo voluptate.
                      name: z
                    - environment:
                        - Voluptatem laboriosam perspiciatis est.
                        - Est veritatis.
                        - Quo aut recusandae.
                        - Temporibus asperiores et voluptatem a consequatur ut.
                      files:
                        - Voluptatem necessitatibus labore aliquam consequatur est.
                        - Ullam voluptate esse.
                        - Aut et totam voluptatem quia illo voluptate.
                      name: z
                - image: Quisquam sed.
                  name: Dignissimos et nemo sunt commodi iste.
                  services:
                    - Rem fugiat est.
                    - Quas enim magnam libero consectetur qui nesciunt.
                    - Quam libero.
                  usedParams:
                    - environment:
                        - Voluptatem laboriosam perspiciatis est.
                        - Est veritatis.
                        - Quo aut recusandae.
                        - Temporibus asperiores et voluptatem a consequatur ut.
                      files:
                        - Voluptatem necessitatibus labore aliquam consequatur est.
                        - Ullam voluptate esse.
                        - Aut et totam voluptatem quia illo voluptate.
                      name: z
                    - environment:
                        - Voluptatem laboriosam perspiciatis est.
                        - Est veritatis.
                        - Quo aut recusandae.
                        - Temporibus asperiores et voluptatem a consequatur ut.
                      files:
                        - Voluptatem necessitatibus labore aliquam consequatur est.
                        - Ullam voluptate esse.
                        - Aut et totam voluptatem quia illo voluptate.
                      name: z
                - image: Quisquam sed.
                  name: Dignissimos et nemo sunt commodi iste.
                  services:
                    - Rem fugiat est.
                    - Quas enim magnam libero consectetur qui nesciunt.
                    - Quam libero.
                  usedParams:
                    - environment:
                        - Voluptatem laboriosam perspiciatis est.
                        - Est veritatis.
                        - Quo aut recusandae.
                        - Temporibus asperiores et voluptatem a consequatur ut.
                      files:
                        - Voluptatem necessitatibus labore aliquam consequatur est.
                        - Ullam voluptate esse.
                        - Aut et totam voluptatem quia illo voluptate.
                      name: z
                    - environment:
                        - Voluptatem laboriosam perspiciatis est.
                        - Est veritatis.
                        - Quo aut recusandae.
                        - Temporibus asperiores et voluptatem a consequatur ut.
                      files:
                        - Voluptatem necessitatibus labore aliquam consequatur est.
                        - Ullam voluptate esse.
                        - Aut et totam voluptatem quia illo voluptate.
                      name: z
            name: Quidem quasi.
            params:
                - name: bym
                  source: static
                  type: bool
                - name: bym
                  source: static
                  type: bool
                - name: bym
                  source: static
                  type: bool
                - name: bym
                  source: static
                  type: bool
        required:
            - name
            - containers
    ParameterRequestBody:
        title: ParameterRequestBody
        type: object
        properties:
            name:
                type: string
                example: p
                minLength: 1
            source:
                type: string
                example: configurable
                enum:
                    - static
                    - generated
                    - configurable
            type:
                type: string
                example: password
                enum:
                    - string
                    - int
                    - bool
                    - password
        example:
            name: x
            source: configurable
            type: int
        required:
            - name
            - source
            - type
    ParameterResponseBody:
        title: ParameterResponseBody
        type: object
        properties:
            name:
                type: string
                example: z
                minLength: 1
            source:
                type: string
                example: generated
                enum:
                    - static
                    - generated
                    - configurable
            type:
                type: string
                example: string
                enum:
                    - string
                    - int
                    - bool
                    - password
        example:
            name: to
            source: configurable
            type: string
        required:
            - name
            - source
            - type
    ParameterUsageRequestBody:
        title: ParameterUsageRequestBody
        type: object
        properties:
            environment:
                type: array
                items:
                    type: string
                    example: Veniam provident ut quibusdam.
                example:
                    - Molestiae aut.
                    - Rerum eos sed sed.
                    - Earum veritatis perferendis.
            files:
                type: array
                items:
                    type: string
                    example: Omnis quaerat neque doloribus.
                example:
                    - Culpa est explicabo ut.
                    - Iusto ad quod consequatur.
                    - Sit similique rerum pariatur quaerat est.
                    - Sit aliquam est.
            name:
                type: string
                example: j6
                minLength: 1
        example:
            environment:
                - Fugit a esse ut.
                - Dolores optio doloremque et a repudiandae.
                - Quos sit facilis aliquid.
                - Numquam in dolorum dolor.
            files:
                - Impedit rerum.
                - Natus debitis voluptate et porro.
            name: kn
    ParameterUsageResponseBody:
        title: ParameterUsageResponseBody
        type: object
        properties:
            environment:
                type: array
                items:
                    type: string
                    example: Molestiae quisquam quas qui voluptates distinctio ut.
                example:
                    - Commodi esse ut et quis accusantium sunt.
                    - Voluptatum nam distinctio.
                    - Amet similique ad laudantium autem unde voluptas.
                    - Qui sequi modi laborum ipsa est quaerat.
            files:
                type: array
                items:
                    type: string
                    example: Mollitia quam voluptatem magnam non voluptatibus.
                example:
                    - Vel tempora.
                    - Deserunt non minus quibusdam maxime.
                    - Amet id dolores qui id et.
            name:
                type: string
                example: "y"
                minLength: 1
        example:
            environment:
                - Eius laborum nostrum vero dolores consequatur.
                - Qui suscipit assumenda iste quis.
            files:
                - Sed inventore.
                - Ut nesciunt ex fugit eum consequatur.
                - Qui beatae maiores.
                - Consequatur reiciendis asperiores.
            name: lq
