openapi: 3.0.3
info:
    title: Api for deployments
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /api/deployments:
        get:
            tags:
                - deployments
            summary: list deployments
            operationId: deployments#list
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                                    example: Quisquam praesentium iure repudiandae temporibus.
                                example:
                                    - Ex quas harum in temporibus repellat omnis.
                                    - Sit consectetur qui velit debitis culpa assumenda.
                            example:
                                - Omnis dolores neque dolore.
                                - Qui doloribus error porro magni molestiae error.
                                - Molestiae sit.
        post:
            tags:
                - deployments
            summary: upsert deployments
            operationId: deployments#upsert
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpsertRequestBody'
                        example:
                            containers:
                                - image: Quisquam sed.
                                  name: Dignissimos et nemo sunt commodi iste.
                                  services:
                                    - Rem fugiat est.
                                    - Quas enim magnam libero consectetur qui nesciunt.
                                    - Quam libero.
                                  usedParams:
                                    - environment:
                                        - Voluptatem laboriosam perspiciatis est.
                                        - Est veritatis.
                                        - Quo aut recusandae.
                                        - Temporibus asperiores et voluptatem a consequatur ut.
                                      files:
                                        - Voluptatem necessitatibus labore aliquam consequatur est.
                                        - Ullam voluptate esse.
                                        - Aut et totam voluptatem quia illo voluptate.
                                      name: z
                                    - environment:
                                        - Voluptatem laboriosam perspiciatis est.
                                        - Est veritatis.
                                        - Quo aut recusandae.
                                        - Temporibus asperiores et voluptatem a consequatur ut.
                                      files:
                                        - Voluptatem necessitatibus labore aliquam consequatur est.
                                        - Ullam voluptate esse.
                                        - Aut et totam voluptatem quia illo voluptate.
                                      name: z
                                - image: Quisquam sed.
                                  name: Dignissimos et nemo sunt commodi iste.
                                  services:
                                    - Rem fugiat est.
                                    - Quas enim magnam libero consectetur qui nesciunt.
                                    - Quam libero.
                                  usedParams:
                                    - environment:
                                        - Voluptatem laboriosam perspiciatis est.
                                        - Est veritatis.
                                        - Quo aut recusandae.
                                        - Temporibus asperiores et voluptatem a consequatur ut.
                                      files:
                                        - Voluptatem necessitatibus labore aliquam consequatur est.
                                        - Ullam voluptate esse.
                                        - Aut et totam voluptatem quia illo voluptate.
                                      name: z
                                    - environment:
                                        - Voluptatem laboriosam perspiciatis est.
                                        - Est veritatis.
                                        - Quo aut recusandae.
                                        - Temporibus asperiores et voluptatem a consequatur ut.
                                      files:
                                        - Voluptatem necessitatibus labore aliquam consequatur est.
                                        - Ullam voluptate esse.
                                        - Aut et totam voluptatem quia illo voluptate.
                                      name: z
                            name: Necessitatibus et autem placeat et.
                            params:
                                - name: bym
                                  source: static
                                  type: bool
                                - name: bym
                                  source: static
                                  type: bool
                                - name: bym
                                  source: static
                                  type: bool
            responses:
                "204":
                    description: No Content response.
    /api/deployments/{deploymentName}:
        get:
            tags:
                - deployments
            summary: get deployments
            operationId: deployments#get
            parameters:
                - name: deploymentName
                  in: path
                  description: Name of the Deployment
                  required: true
                  schema:
                    type: string
                    description: Name of the Deployment
                    example: Iusto vel.
                  example: Et occaecati eveniet voluptatem veritatis ducimus.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UpsertRequestBody'
                            example:
                                containers:
                                    - image: Eos nostrum adipisci.
                                      name: Aut molestiae vero tempore quasi.
                                      services:
                                        - Enim unde consequatur amet iusto.
                                        - Expedita fuga.
                                        - Libero reprehenderit mollitia repellendus provident.
                                        - Autem vitae ea adipisci itaque qui ut.
                                      usedParams:
                                        - environment:
                                            - Veritatis ea.
                                            - Placeat dolore asperiores.
                                            - Vitae omnis architecto maxime nesciunt voluptatibus.
                                          files:
                                            - Aut reprehenderit ad odit est.
                                            - Fugit deserunt hic a architecto.
                                            - Commodi reprehenderit.
                                            - Sed est enim quidem ad illum distinctio.
                                          name: "7"
                                        - environment:
                                            - Veritatis ea.
                                            - Placeat dolore asperiores.
                                            - Vitae omnis architecto maxime nesciunt voluptatibus.
                                          files:
                                            - Aut reprehenderit ad odit est.
                                            - Fugit deserunt hic a architecto.
                                            - Commodi reprehenderit.
                                            - Sed est enim quidem ad illum distinctio.
                                          name: "7"
                                name: Iusto est quae eaque animi a.
                                params:
                                    - name: tj
                                      source: static
                                      type: password
                                    - name: tj
                                      source: static
                                      type: password
                "404":
                    description: 'DeploymentNotFound: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/deployments/{deploymentName}/delete:
        get:
            tags:
                - deployments
            summary: delete deployments
            operationId: deployments#delete
            parameters:
                - name: deploymentName
                  in: path
                  description: Name of the Deployment
                  required: true
                  schema:
                    type: string
                    description: Name of the Deployment
                    example: Sit quibusdam dolorem qui omnis eum.
                  example: Sunt laudantium aspernatur non vero.
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'DeploymentNotFound: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/deployments/{deploymentName}/view:
        get:
            tags:
                - deployments
            summary: get deployments
            operationId: deployments#get#1
            parameters:
                - name: deploymentName
                  in: path
                  description: Name of the Deployment
                  required: true
                  schema:
                    type: string
                    description: Name of the Deployment
                    example: Autem dolor quod ut sit.
                  example: Et quisquam quasi nihil.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UpsertRequestBody'
                            example:
                                containers:
                                    - image: Eos nostrum adipisci.
                                      name: Aut molestiae vero tempore quasi.
                                      services:
                                        - Enim unde consequatur amet iusto.
                                        - Expedita fuga.
                                        - Libero reprehenderit mollitia repellendus provident.
                                        - Autem vitae ea adipisci itaque qui ut.
                                      usedParams:
                                        - environment:
                                            - Veritatis ea.
                                            - Placeat dolore asperiores.
                                            - Vitae omnis architecto maxime nesciunt voluptatibus.
                                          files:
                                            - Aut reprehenderit ad odit est.
                                            - Fugit deserunt hic a architecto.
                                            - Commodi reprehenderit.
                                            - Sed est enim quidem ad illum distinctio.
                                          name: "7"
                                        - environment:
                                            - Veritatis ea.
                                            - Placeat dolore asperiores.
                                            - Vitae omnis architecto maxime nesciunt voluptatibus.
                                          files:
                                            - Aut reprehenderit ad odit est.
                                            - Fugit deserunt hic a architecto.
                                            - Commodi reprehenderit.
                                            - Sed est enim quidem ad illum distinctio.
                                          name: "7"
                                name: Iusto est quae eaque animi a.
                                params:
                                    - name: tj
                                      source: static
                                      type: password
                                    - name: tj
                                      source: static
                                      type: password
                "404":
                    description: 'DeploymentNotFound: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /openapi3.json:
        get:
            tags:
                - deployments
            summary: Download ./gen/http/openapi3.json
            operationId: deployments#/openapi3.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        Container:
            type: object
            properties:
                image:
                    type: string
                    example: Facilis natus qui et ipsam et.
                name:
                    type: string
                    example: Laudantium repudiandae.
                services:
                    type: array
                    items:
                        type: string
                        example: Quaerat accusantium est qui earum.
                    example:
                        - Harum vero consequatur numquam vel eos provident.
                        - Est et.
                usedParams:
                    type: array
                    items:
                        $ref: '#/components/schemas/ParameterUsage'
                    example:
                        - environment:
                            - Voluptatem laboriosam perspiciatis est.
                            - Est veritatis.
                            - Quo aut recusandae.
                            - Temporibus asperiores et voluptatem a consequatur ut.
                          files:
                            - Voluptatem necessitatibus labore aliquam consequatur est.
                            - Ullam voluptate esse.
                            - Aut et totam voluptatem quia illo voluptate.
                          name: z
                        - environment:
                            - Voluptatem laboriosam perspiciatis est.
                            - Est veritatis.
                            - Quo aut recusandae.
                            - Temporibus asperiores et voluptatem a consequatur ut.
                          files:
                            - Voluptatem necessitatibus labore aliquam consequatur est.
                            - Ullam voluptate esse.
                            - Aut et totam voluptatem quia illo voluptate.
                          name: z
                        - environment:
                            - Voluptatem laboriosam perspiciatis est.
                            - Est veritatis.
                            - Quo aut recusandae.
                            - Temporibus asperiores et voluptatem a consequatur ut.
                          files:
                            - Voluptatem necessitatibus labore aliquam consequatur est.
                            - Ullam voluptate esse.
                            - Aut et totam voluptatem quia illo voluptate.
                          name: z
                        - environment:
                            - Voluptatem laboriosam perspiciatis est.
                            - Est veritatis.
                            - Quo aut recusandae.
                            - Temporibus asperiores et voluptatem a consequatur ut.
                          files:
                            - Voluptatem necessitatibus labore aliquam consequatur est.
                            - Ullam voluptate esse.
                            - Aut et totam voluptatem quia illo voluptate.
                          name: z
            example:
                image: Et autem.
                name: Facilis illo labore dolor autem et eveniet.
                services:
                    - Nulla deleniti ducimus repellendus reprehenderit omnis.
                    - Libero facere in nisi.
                    - Eveniet et.
                    - Libero illum omnis provident odit.
                usedParams:
                    - environment:
                        - Voluptatem laboriosam perspiciatis est.
                        - Est veritatis.
                        - Quo aut recusandae.
                        - Temporibus asperiores et voluptatem a consequatur ut.
                      files:
                        - Voluptatem necessitatibus labore aliquam consequatur est.
                        - Ullam voluptate esse.
                        - Aut et totam voluptatem quia illo voluptate.
                      name: z
                    - environment:
                        - Voluptatem laboriosam perspiciatis est.
                        - Est veritatis.
                        - Quo aut recusandae.
                        - Temporibus asperiores et voluptatem a consequatur ut.
                      files:
                        - Voluptatem necessitatibus labore aliquam consequatur est.
                        - Ullam voluptate esse.
                        - Aut et totam voluptatem quia illo voluptate.
                      name: z
                    - environment:
                        - Voluptatem laboriosam perspiciatis est.
                        - Est veritatis.
                        - Quo aut recusandae.
                        - Temporibus asperiores et voluptatem a consequatur ut.
                      files:
                        - Voluptatem necessitatibus labore aliquam consequatur est.
                        - Ullam voluptate esse.
                        - Aut et totam voluptatem quia illo voluptate.
                      name: z
            required:
                - name
                - image
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        Parameter:
            type: object
            properties:
                name:
                    type: string
                    example: "4"
                    minLength: 1
                source:
                    type: string
                    example: generated
                    enum:
                        - static
                        - generated
                        - configurable
                type:
                    type: string
                    example: bool
                    enum:
                        - string
                        - int
                        - bool
                        - password
            example:
                name: 5u
                source: static
                type: int
            required:
                - name
                - source
                - type
        ParameterUsage:
            type: object
            properties:
                environment:
                    type: array
                    items:
                        type: string
                        example: Sunt consequuntur error est.
                    example:
                        - Natus facere aut nemo in impedit.
                        - Consequatur praesentium nihil quisquam cumque.
                        - In ut sit ipsa et.
                files:
                    type: array
                    items:
                        type: string
                        example: Voluptatem accusantium dolor qui nihil officia.
                    example:
                        - Nihil optio et dolores.
                        - Eius qui eius.
                name:
                    type: string
                    example: au
                    minLength: 1
            example:
                environment:
                    - Sunt pariatur possimus delectus.
                    - Eum ipsum omnis in ipsam reprehenderit.
                    - Praesentium consectetur et rerum et.
                    - Dignissimos blanditiis illum.
                files:
                    - Et adipisci dolorem sit tenetur rerum.
                    - Voluptatem et sint deleniti veniam.
                    - Itaque et.
                    - Ut eligendi in omnis amet sequi.
                name: j
        UpsertRequestBody:
            type: object
            properties:
                containers:
                    type: array
                    items:
                        $ref: '#/components/schemas/Container'
                    example:
                        - image: Quisquam sed.
                          name: Dignissimos et nemo sunt commodi iste.
                          services:
                            - Rem fugiat est.
                            - Quas enim magnam libero consectetur qui nesciunt.
                            - Quam libero.
                          usedParams:
                            - environment:
                                - Voluptatem laboriosam perspiciatis est.
                                - Est veritatis.
                                - Quo aut recusandae.
                                - Temporibus asperiores et voluptatem a consequatur ut.
                              files:
                                - Voluptatem necessitatibus labore aliquam consequatur est.
                                - Ullam voluptate esse.
                                - Aut et totam voluptatem quia illo voluptate.
                              name: z
                            - environment:
                                - Voluptatem laboriosam perspiciatis est.
                                - Est veritatis.
                                - Quo aut recusandae.
                                - Temporibus asperiores et voluptatem a consequatur ut.
                              files:
                                - Voluptatem necessitatibus labore aliquam consequatur est.
                                - Ullam voluptate esse.
                                - Aut et totam voluptatem quia illo voluptate.
                              name: z
                    minItems: 1
                name:
                    type: string
                    example: Deleniti non.
                params:
                    type: array
                    items:
                        $ref: '#/components/schemas/Parameter'
                    example:
                        - name: bym
                          source: static
                          type: bool
                        - name: bym
                          source: static
                          type: bool
            example:
                containers:
                    - image: Quisquam sed.
                      name: Dignissimos et nemo sunt commodi iste.
                      services:
                        - Rem fugiat est.
                        - Quas enim magnam libero consectetur qui nesciunt.
                        - Quam libero.
                      usedParams:
                        - environment:
                            - Voluptatem laboriosam perspiciatis est.
                            - Est veritatis.
                            - Quo aut recusandae.
                            - Temporibus asperiores et voluptatem a consequatur ut.
                          files:
                            - Voluptatem necessitatibus labore aliquam consequatur est.
                            - Ullam voluptate esse.
                            - Aut et totam voluptatem quia illo voluptate.
                          name: z
                        - environment:
                            - Voluptatem laboriosam perspiciatis est.
                            - Est veritatis.
                            - Quo aut recusandae.
                            - Temporibus asperiores et voluptatem a consequatur ut.
                          files:
                            - Voluptatem necessitatibus labore aliquam consequatur est.
                            - Ullam voluptate esse.
                            - Aut et totam voluptatem quia illo voluptate.
                          name: z
                    - image: Quisquam sed.
                      name: Dignissimos et nemo sunt commodi iste.
                      services:
                        - Rem fugiat est.
                        - Quas enim magnam libero consectetur qui nesciunt.
                        - Quam libero.
                      usedParams:
                        - environment:
                            - Voluptatem laboriosam perspiciatis est.
                            - Est veritatis.
                            - Quo aut recusandae.
                            - Temporibus asperiores et voluptatem a consequatur ut.
                          files:
                            - Voluptatem necessitatibus labore aliquam consequatur est.
                            - Ullam voluptate esse.
                            - Aut et totam voluptatem quia illo voluptate.
                          name: z
                        - environment:
                            - Voluptatem laboriosam perspiciatis est.
                            - Est veritatis.
                            - Quo aut recusandae.
                            - Temporibus asperiores et voluptatem a consequatur ut.
                          files:
                            - Voluptatem necessitatibus labore aliquam consequatur est.
                            - Ullam voluptate esse.
                            - Aut et totam voluptatem quia illo voluptate.
                          name: z
                    - image: Quisquam sed.
                      name: Dignissimos et nemo sunt commodi iste.
                      services:
                        - Rem fugiat est.
                        - Quas enim magnam libero consectetur qui nesciunt.
                        - Quam libero.
                      usedParams:
                        - environment:
                            - Voluptatem laboriosam perspiciatis est.
                            - Est veritatis.
                            - Quo aut recusandae.
                            - Temporibus asperiores et voluptatem a consequatur ut.
                          files:
                            - Voluptatem necessitatibus labore aliquam consequatur est.
                            - Ullam voluptate esse.
                            - Aut et totam voluptatem quia illo voluptate.
                          name: z
                        - environment:
                            - Voluptatem laboriosam perspiciatis est.
                            - Est veritatis.
                            - Quo aut recusandae.
                            - Temporibus asperiores et voluptatem a consequatur ut.
                          files:
                            - Voluptatem necessitatibus labore aliquam consequatur est.
                            - Ullam voluptate esse.
                            - Aut et totam voluptatem quia illo voluptate.
                          name: z
                name: Reprehenderit at accusantium earum ut ex.
                params:
                    - name: bym
                      source: static
                      type: bool
                    - name: bym
                      source: static
                      type: bool
                    - name: bym
                      source: static
                      type: bool
            required:
                - name
                - containers
tags:
    - name: deployments
      description: used to manage active deployments
